-- CreateEnum
CREATE TYPE "EventCategory" AS ENUM ('CONFERENCE', 'WORKSHOP', 'SEMINAR', 'NETWORKING', 'SOCIAL', 'TECH', 'BUSINESS', 'ARTS', 'SPORTS', 'EDUCATION', 'ENTERTAINMENT', 'COMMUNITY', 'OTHER');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "category" "EventCategory" NOT NULL DEFAULT 'OTHER';
